lsi: false
url: https://sdumetz.github.io
title: Sebastien Dumetz's Blog
description: A blog on my various creation experiences
source: .
exclude:
  - node_modules
  - src
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-feed
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
