lsi: false
url: https://sdumetz.github.io
source: .
exclude:
  - node_modules
  - src
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-feed
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
